### ISSUE TITLE
dns!   Error starting cluster: wait: waiting for k8s-app=kube-dns

### ISSUE THREAD

**Issue by jweidley** [nre-learning/antidote-selfmedicate#11]
On a band new Ubuntu 16.04 install, when starting selfmedicate (./selfmedicate.sh start ../antidote) minikube crashes. Here is the full error message:

:   Waiting for pods: apiserver proxy etcd scheduler controller addon-manager dns!   Error starting cluster: wait: waiting for k8s-app=kube-dns: timed out waiting for the condition

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by jweidley** [comment]
This problem appears to be related with minikube v0.35. Downloaded minikube v0.34.1 from the URL below and it starts up without issue.

https://storage.googleapis.com/minikube/releases/v0.34.1/minikube-linux-amd64

**Comment by Mierdin** [comment]
@jweidley Thanks for the report. I'll update the selfmedicate docs to indicate you should use v0.34.1, and maybe add an enforcement in the script.

**Comment by Mierdin** [comment]
Done in https://github.com/nre-learning/antidote/commit/6bdce52cb1096df0803637066e4626fe43f4ba58
