### ISSUE TITLE
tab completion and native linux support

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote-selfmedicate#14]

**Comment by cloudtoad** [comment]
Closing out issue.

**Comment by Mierdin** [comment]
I'd still like to incorporate kubectl tab completion now that we have a Vagrant machine and we can control that fairly easily.

However, I did a horrible job of encaping that in the title or description so I'll open a new issue to do this and generally get the old selfmedicate style (sans-vagrant) decommissioned.
