### ISSUE TITLE
./selfmedicate.sh start fails with error: 'cp: ~/.kube/config: No such file or directory'

### ISSUE THREAD

**Issue by Collisio-Adolebitque** [nre-learning/antidote-selfmedicate#15]
Software installed:

- VirtualBox 6.0 from https://www.virtualbox.org/wiki/Downloads
- kubectl v1.14.0 via ```brew install kubernetes-cli```
- minikube v0.34.1 via ```curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.34.1/minikube-darwin-amd64 && chmod +x minikube && sudo cp minikube /usr/local/bin/ && rm minikube```

Cloned the antidote and antidote-selfmedicate repos into the same root directory.

Error received:

```
lab:antidote-selfmedicate collisio$ ./selfmedicate.sh start
Backing up existing kubeconfig to ~/.kube/preminikube_bkp...
cp: ~/.kube/config: No such file or directory
```
The script is correct, there is no ~/.kube/ directory.

Any ideas?

**Comment by Mierdin** [comment]
Thanks for reporting this, and for the detailed setup information.
Added a fix in https://github.com/nre-learning/antidote-selfmedicate/pull/16, to only try backing up an old kubeconfig if the `.kube` directory exists, which it won't if you've never run this before.

Thanks again!
