### ISSUE TITLE
Missing install instructions for clone of nrelabs-curriculum

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-selfmedicate#18]
When only cloning https://github.com/nre-learning/antidote-selfmedicate as instructed in https://antidoteproject.readthedocs.io/en/latest/building/local.html, ./selfmedicate.sh start
will fail as it won't be able to start the lessons:
```
./selfmedicate.sh start
Error - ../nrelabs-curriculum doesn't look like a proper curriculum directory.
Either this directory wasn't found, or the subdirectory 'lessons' within that directory wasn't found.

In either case, this script cannot continue. Please either place the appropriate directory in place, or
edit the LESSON_DIRECTORY variable at the top of this script.
```
I guess instructions should ask to clone https://github.com/nre-learning/nrelabs-curriculum alongside antidote-selfmedicate.

Hope this helps,

**Comment by psychemedia** [comment]
Also, the docs suggest that the path to the sibling cloned curriculum repo should be `../antidote` whereas if you clone the lesson repo directly the line in `selfmedicate.sh` file should be:

`LESSON_DIRECTORY="../nrelabs-curriculum"`

**Comment by cloudtoad** [comment]
Documentation updated.
