### ISSUE TITLE
Add kubectl installation to prerequisites to selfmedicate.sh

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-selfmedicate#19]
If only minikube is installed locally, the cluster gets started, but the script later fails on missing kubectl.

instructions should then require installation of kubectl too.

**Comment by psychemedia** [comment]
On a Mac, I think the `brew cask install minikube` route may do this automatically...?

Hmmm... or maybe it doesn't. I thinkI've used *docker-kubernetes* in the past so maybe I had `kubectl` from then... 

In which case: `brew install kubernetes-cli`

**Comment by cloudtoad** [comment]
Documentation updated
