### ISSUE TITLE
Installation Docs - Discussion

### ISSUE THREAD

**Issue by netmanchris** [nre-learning/antidote-selfmedicate#2]
TL/DL:  Would like to work on docs for installation of self-medicate piece on OSX.  Going through process and will submit a PR with more detail. Finding spots that i think a non-dev/Linux skilled networking engineer might get stuck or confused. 

[Question]
Any guidance on where the
 git clone https://github.com/nre-learning/antidote-selfmedicate

Should be cloned to?  Should assume that network engineers don’t know where to put things. What guidance do we want to give them? Given that iCloud sync can automatically remove local cache of files on desktop/documents I’d like to recommend creating a folder in a non-icloud-sync’d location.  

Thoughts?

**Comment by Mierdin** [comment]
Hm....while I agree in principle to making things easy for folks that don't have experience with this stuff (they are indeed the target audience for antidote and NRE Labs in general), the idea of "running this yourself" implies a bit more responsibility and knowledge of at least your own system. If there's easy things we can do to make it simpler to spin it up, or make the docs clearer, we should do it, but I think a question like where to clone the repo isn't something we need to get into. There's nothing on our side that mandates this location.

**Comment by cloudtoad** [comment]
Just a heads up, this is 11 months old... I'll be closing this out.  The installation instructions in the docs work for MacOS.
