### ISSUE TITLE
Make it an option to use qemu/kvm for minikube for better performance

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-selfmedicate#21]
Minikube can be run with the --vm-driver kvm2 option (see https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver) to use a qemu/kvm VM instead of VirtualBox, when on Linux, and if the machine handles nested-virtualization.

I've juste added the option to selfmedicate.sh and the labs seem a bit faster from what I can see on my machine.

Of course YMMV, and a proper benchmark could be necessary.

I guess it could be made optional when/if people are running the script on Linux, and libvirt and other requirements are met, of course.

Other than that I'm not so sure everything else is the same, like mounting stuff to the guest VM...

Hope this helps,

**Comment by cloudtoad** [comment]
Did you just add/replace that option in the script or did you make it optional via some command-line argument?

**Comment by olberger** [comment]
I just added the option to minikube start inside the script, for the moment.

**Comment by cloudtoad** [comment]
Alright, I'll work on making it a command-line option...

**Comment by olberger** [comment]
Btw, I think @blinklet used that approach when testing Antidote: http://www.brianlinkletter.com/install-antidote-nre-labs-network-emulator-linux/
