### ISSUE TITLE
Lesson endpoint shells do not launch

### ISSUE THREAD

**Issue by blinklet** [nre-learning/antidote-selfmedicate#26]
When I start a lesson, the shell remains blank on any node in the lesson. For example, when I start the "introduction to YAML" lesson, the network endpoint "Linux1" terminal window just show a blank, black screen.

**Comment by blinklet** [comment]
Update: it seems to be working again. When I saw the problem, I was connected to an satellite Internet connect with a long round-trip delay (pings are over 1000 ms). Maybe that was a factor? Now I am on a terrestrial Internet connection with normal ping times and the shell launches OK.

**Comment by cloudtoad** [comment]
Closing issue.
