### ISSUE TITLE
Useless copyright mention in LICENSE file

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-selfmedicate#35]
I guess the Apache 2 licence text isn't really copyrighted by Juniper. I'd then suggest to remove that first line from the LICENSE file.

https://github.com/nre-learning/antidote-selfmedicate/blob/b1a9008cd366cae29b18ae20573471ec897cf03b/LICENSE#L1

**Comment by cloudtoad** [comment]
Copyright line removed and merged....  Closing issue.
