### ISSUE TITLE
Problem mounting NFS shared forlder for /antidote

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-selfmedicate#41]
Maybe it's my particular setup, but I've hit the following problem :
```
=> Antidote 0.4.0: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 192.168.34.1:/home/olivier/git/github.com/nre-learning/nrelabs-curriculum /antidote

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported

```
where /home/olivier/git/github.com/nre-learning/nrelabs-curriculum exists...

I guess this might be related to some shared folder driver issue... I kind of remember there may be problems on some non-standard kernel modules in the virtualbox extensions and such...

I'm running Debian testing, and VirtualBox reports of a mismatch of versions, rebuilds the modules in the guest and reboots it... 

Hope I'm not alone ;)

**Comment by olberger** [comment]
It seems that changing the shared folder line to remove the exact requirement on NFS helped:
```
config.vm.synced_folder "../nrelabs-curriculum", "/antidote"
```
Maybe that's not portable ? Or there are issues of replication of changes made to the curriculum betw host/guest then ?

Hope this helps,

**Comment by Mierdin** [comment]
I don't see a problem removing the requirement to use NFS - @smk4664 any issues with this?

I am curious what's used if you don't specify - the Vagrant docs don't seem to say.

**Comment by olberger** [comment]
Dunno... some scp-like sync of the files ?... or some custom VirtualBox module at work ?

**Comment by smk4664** [comment]
Let me check the docs on that.  Maybe there is a way to default when NFS is not supported.

**Comment by smk4664** [comment]
https://www.vagrantup.com/docs/synced-folders/nfs.html  Provides good details on this.  Turns out Windows just ignores the configuration and Linux expects you to install the packages...  I am good with removing NFS. The default uses virtualbox, so this would only work when virtualbox is the host.

**Comment by olberger** [comment]
I've prepared a branch where I removed that requirement if anyone wants to test (including my students) : https://github.com/olberger/antidote-selfmedicate/tree/linuxtests

**Comment by smk4664** [comment]
Thank you, I just moved my Windows machine over to Hyper-V, so I need to explore getting SMB to work.  I think the better route to go is to select which version of shared folders based on the Provider.
