### ISSUE TITLE
Update base vagrant box to 18.04 or later ?

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-selfmedicate#42]
The base box is bento/ubuntu-16.04, and I wonder whether it could be updated to a more recent version with benefits (or drawbacks)...

Not specifically and issue per se if everything works OK k8s-wise...

**Comment by Mierdin** [comment]
I'm not opposed to this long-term, but let's keep on 16 for a few months while we iron out the wrinkles with the new Vagrant approach.

**Comment by smk4664** [comment]
I don't see an issue trying 18.04 LTS.  You should be able to change the base box and try.  I knew 16.04 was supported by k8s, which is why I went with that.

**Comment by olberger** [comment]
I've made a test with generic/ubuntu1804 (with libvirt - see #47), which seems OK. haven't tested complex lessons though.

Hth,

**Comment by olberger** [comment]
There seems to be an issue with 18.04. I noticed that the 2 coredns pods are CrashLoopBackOff

$ kubectl logs -n kube-system pod/coredns-fb8b8dccf-2pfkx
```
.:53
2020-04-15T19:44:40.924Z [INFO] CoreDNS-1.3.1
2020-04-15T19:44:40.924Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2020-04-15T19:44:40.924Z [INFO] plugin/reload: Running configuration MD5 = 599b9eb76b8c147408aed6a0bbe0f669
2020-04-15T19:44:40.925Z [FATAL] plugin/loop: Loop (127.0.0.1:35014 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 6765374243513466661.7774155304363661349."
```
Maybe that won't harm much... but suboptimal

**Comment by olberger** [comment]
This very much ressembles https://coredns.io/plugins/loop/#troubleshooting-loops-in-kubernetes-clusters
A possible workaround seems to add "--extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf" to minikube upon startup

**Comment by olberger** [comment]
Now that 20.04 is out, I think it would be reasonable to upgrade to 18.04. Will keep on testing with it on my side.
