### ISSUE TITLE
Add a message about the missing hostsupdater plugin in Vagrantfile

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-selfmedicate#45]
One should not run vagrant up if the hostsupdater plugin isn't there... however this may not be a blocker.

In such case, maybe a warning message could be useful, for instance at the end of the provisionning down in the Vagrantfile, with something like:
```
  if not defined?(VagrantPlugins::HostsUpdater)
    config.vm.provision "shell", privileged: false, inline: <<-EOF
      echo "You should install the Vagrant::Hostsupdater plugin to support configuration of the 'antidote-local' hostname."
    EOF
  end
```

**Comment by smk4664** [comment]
That's a great idea.  HostsUpdater is not required, but very helpful.

**Comment by olberger** [comment]
Well... it seems it's rather necessary (or the user needs to apply the change manually): see https://github.com/nre-learning/antidote-selfmedicate/issues/39#issuecomment-539682914

**Comment by Mierdin** [comment]
I'm going to close this - hostsupdater is a requirement but I don't think it's necessary to add a blocking check. It's in the docs, so if someone doesn't want to follow the docs, they're on their own.
