### ISSUE TITLE
Modifications to use SelfMedicate with Kubernetes latest version

### ISSUE THREAD

**Issue by isildir77** [nre-learning/antidote-selfmedicate#48]
I installed Kubernetes latest version ( v1.16 ) and the self-medicate.sh script wouldn't run properly. It crashed due to Kubernetes API version updates.

I just had to modify all the yaml files in the antidote-selfmedicate/manifests sub-directory. I just replaced all "extensions/v1beta1" by "apps/v1".

Hope it will help

**Comment by Mierdin** [comment]
This is expected. Syringe, the part of Antidote that communicates with Kubernetes - is built to target a particular version of Kubernetes. In this case, the current stable version v0.4.0 targets v1.14. The selfmedicate manifests are built to reflect this. When Syringe is updated to target a newer version of Kubernetes, the selfmedicate manifests will be upgraded accordingly.
