### ISSUE TITLE
Provisioning should do apt-get update before installs

### ISSUE THREAD

**Issue by olberger** [nre-learning/antidote-selfmedicate#49]
I've had issues with downloading libc-dev package during virtualbox modules rebuild due to version mismatch, which is done automatically by Vagrant AFAIU... and having a look at the provisioning script I noticed there doesn't seem to be any apt-get update before the first apt-get install for docker-ce installation.

Maybe not a huge issue, but maybe worth updating first.

Hth

**Comment by smk4664** [comment]
Thanks!  I will add this in to the script.

**Comment by olberger** [comment]
Thanks... actually, it seems it may not be Vagrant which does this, but the vbguest plugin which fails (without a clear mention, hence my confusion) : https://github.com/dotless-de/vagrant-vbguest/issues/351

But in any case, performing an apt update is probably good before any apt install, in case the image hasn't kept a still balid image of the available packages, if minor releases have been issued in between (security updates).

**Comment by smk4664** [comment]
The apt-get update is done during the docker-repo stage. Closing this issue.
