### ISSUE TITLE
Running antidote-selfmedicate locally is broken by netskope on Juniper corporate laptop

### ISSUE THREAD

**Issue by mmellin** [nre-learning/antidote-selfmedicate#9]
Locally running NRE labs via minikube and virtualbox on OSX crashes when Netskope intercepts SSL web calls to `storage.googleapis.com` and `k8s.gcr.io`.    To get around these issues corporate laptops need to reach out to IT, create a case, and receive the following certs:

- `netskopeint.pem` (intermediate cert)
- `netskoperoot.pem` (root cert)

After this the user must make a directory structure under `~/.minikube` and copy in certificates:

` $ mkdir -p ~/.minikube/files/etc/ssl/certs`
` $ cp netskopeint.pem ~/.minikube/etc/files/ssl/certs`
` $ cp netskoperoot.pem ~/.minikube/etc/files/ssl/certs`

        NOTE: verify permissions are at least 644 at least on these cert files.

`$ minikube start` or `./anti-up.sh` should now function

**Comment by cloudtoad** [comment]
Closing this issue out.
